### ISSUE TITLE
Open in Unity 5 Personal?

### ISSUE THREAD

**Issue by tmboyington** [eamonwoortman/django-unity3d-example#4]
Great project...it will be a big help!

I'm able to open the project and successfully run it using Unity 4.5.2f1.

In Unity 5 Personal I get a message of "No MonoBehaviour scripts in the file, or their names do not match the file name."

**Comment by eamonwoortman** [comment]
Hi there, 

I have been meaning to work on the Unity 5 support but wanted to rewrite some bits first. I will have a quick looksy to see if I can fix it. 

Thanks for filing the issue

**Comment by eamonwoortman** [comment]
Could you give the latest version a go? it should have fixed the issue regarding the www.headers issue(hashtables vs dicts)

**Comment by tmboyington** [comment]
Wow.....thanks for the quick update.
I'm an experienced Flash user, but I've only been using Unity for about a week. Your example project will be a big help in porting my game.
I'm about to head into work, but I'll try to test out the updated project when I get home this evening.

```
  From: Eamon Woortman <notifications@github.com>
```

 To: eamonwoortman/django-unity3d-example django-unity3d-example@noreply.github.com 
Cc: tmboyington tmboyington@yahoo.com 
 Sent: Friday, March 20, 2015 6:41 AM
 Subject: Re: [django-unity3d-example] Open in Unity 5 Personal? (#4)

Could you give the latest version a go? it should have fixed the issue regarding the www.headers issue(hashtables vs dicts)—

**Comment by eamonwoortman** [comment]
Thanks for taking interest in the project. Let me know if it works so I can close the ticket :). 
Also, what project are you porting? Can you let me know when it's finished?

**Comment by tmboyington** [comment]
I was able to download the updated project and open it in Unity 5. It communicated successfully with the included Django backend sample project.
My project is: www.imperiumreclaimed.com
Since this is a hobby, it will take me a while to get it completely ported to Unity. I plan to post my development builds, and I'll let you know when I have my client talking to my Django backend.
Thanks again!

**Comment by eamonwoortman** [comment]
Tested it and it works on Unity5 now. Also, I'm dropping support for earlier versions(<5), if someone still needs to work on Unity4.x, they can grab the 'stable_unity4' tag at https://github.com/eamonwoortman/django-unity3d-example/releases/tag/stable_unity4.
